### PR TITLE
fix line breaks

### PR DESCRIPTION
**Pull request by bhollan**
Edit for line breaks

### CODE REVIEW

**Comment by pletcher** [comment]
:/ It's lame that Learn's markdown rendering doesn't ignore single line breaks. They make it so much easier to see changes.

**Comment by pletcher** [comment]
But 👍 thanks for this!

**Comment by bhollan** [comment]
I can muster up the strength to ignore the weird line breaks if fixing them doesn't really do anything

But what I truly do NOT understand is how they get there.  I've seen a dozen lessons that are mixed with paragraphs broken up, and paragraphs on one-line.

**Comment by pletcher** [comment]
Oh, my bad -- that was me. My editor gets all fussy when a line goes past column 80 -- I'll turn that off in Markdown :)

**Comment by pletcher** [comment]
Well, not just me -- I think some others do it too. But there's something different with how Learn renders Markdown vs. "standard" Markdown:

> A paragraph is simply one or more consecutive lines of text, separated by one or more blank lines. (A blank line is any line that looks like a blank line — a line containing nothing but spaces or tabs is considered blank.) Normal paragraphs should not be indented with spaces or tabs.
- https://daringfireball.net/projects/markdown/basics

So one line break shouldn't trigger a new paragraph, by my reading. But it's all good, it'll be easier for me to adapt than to change our rendering :)

**Pull request merged**
